
using System.Collections.Generic;
using System.Text.Json;
using System;
using System.Text.Json.Serialization;

// Autogenerated 2021-06-06T09:44:39+10:00
namespace SBucket
{
    public class BaseOrganisation {
        
        
                
        [JsonInclude, JsonPropertyName("name")]
        public string Name { get; set; }

            
                
        [JsonInclude, JsonPropertyName("public")]
        public bool Public { get; set; }

            
                
        [JsonInclude, JsonPropertyName("id")]
        public string Id { get; set; }

            
                
        [JsonInclude, JsonPropertyName("active")]
        public bool Active { get; set; }

            
                
        [JsonInclude, JsonPropertyName("createdAt")]
        public DateTime CreatedAt { get; set; }

            
                
        [JsonInclude, JsonPropertyName("updatedAt")]
        public DateTime UpdatedAt { get; set; }

            
                
        [JsonInclude, JsonPropertyName("description")]
        public string Description { get; set; }

            
                
        [JsonInclude, JsonPropertyName("website")]
        public string Website { get; set; }

            
                
        [JsonInclude, JsonPropertyName("email")]
        public string Email { get; set; }

                    
        public string Serialise()
        {
            var options = new JsonSerializerOptions { WriteIndented = true, IncludeFields = true };
            string jsonString = JsonSerializer.Serialize(this, options);
            return jsonString;
        }

        public BaseOrganisation Deserialise(string json)
        {
            
            var deserialised = CreateFromJson(json);

            
            Name = deserialised.Name;
            Public = deserialised.Public;
            Id = deserialised.Id;
            Active = deserialised.Active;
            CreatedAt = deserialised.CreatedAt;
            UpdatedAt = deserialised.UpdatedAt;
            Description = deserialised.Description;
            Website = deserialised.Website;
            Email = deserialised.Email;
            return this;
        }
           

        public static BaseOrganisation CreateFromJson(string json)
        {
            return JsonSerializer.Deserialize<BaseOrganisation>(json);
        }

        public BaseOrganisation()
        {

        }
        
        public BaseOrganisation(string json)
        {
            Deserialise(json);
        }
    }    
}

