
using System.Collections.Generic;
using System.Text.Json;
using System;
using System.Text.Json.Serialization;

// Autogenerated 2021-06-06T09:44:39+10:00
namespace SBucket
{
    public class BasePlayerEvent<T1> {
        
        
                
        [JsonInclude, JsonPropertyName("metadata")]
        public T1 Metadata { get; set; }

            
                
        [JsonInclude, JsonPropertyName("code")]
        public string Code { get; set; }

            
                
        [JsonInclude, JsonPropertyName("playerId")]
        public string PlayerId { get; set; }

            
                
        [JsonInclude, JsonPropertyName("id")]
        public string Id { get; set; }

            
                
        [JsonInclude, JsonPropertyName("active")]
        public bool Active { get; set; }

            
                
        [JsonInclude, JsonPropertyName("createdAt")]
        public DateTime CreatedAt { get; set; }

            
                
        [JsonInclude, JsonPropertyName("updatedAt")]
        public DateTime UpdatedAt { get; set; }

                    
        public string Serialise()
        {
            var options = new JsonSerializerOptions { WriteIndented = true, IncludeFields = true };
            string jsonString = JsonSerializer.Serialize(this, options);
            return jsonString;
        }

        public BasePlayerEvent<T1> Deserialise(string json)
        {
            
            var deserialised = CreateFromJson(json);

            
            Metadata = deserialised.Metadata;
            Code = deserialised.Code;
            PlayerId = deserialised.PlayerId;
            Id = deserialised.Id;
            Active = deserialised.Active;
            CreatedAt = deserialised.CreatedAt;
            UpdatedAt = deserialised.UpdatedAt;
            return this;
        }
           

        public static BasePlayerEvent<T1> CreateFromJson(string json)
        {
            return JsonSerializer.Deserialize<BasePlayerEvent<T1>>(json);
        }

        public BasePlayerEvent()
        {

        }
        
        public BasePlayerEvent(string json)
        {
            Deserialise(json);
        }
    }    
}

