
using System.Collections.Generic;
using System.Text.Json;
using System;
using System.Text.Json.Serialization;

// Autogenerated 2021-06-13T01:13:10+10:00
namespace SBucket
{
    public class BaseUserProvider<T1> {
        
        
                
        [JsonInclude, JsonPropertyName("providerMetadata")]
        public T1 ProviderMetadata { get; set; } = default(T1);

            
                
        [JsonInclude, JsonPropertyName("providerName")]
        public string ProviderName { get; set; } = null;

            
                
        [JsonInclude, JsonPropertyName("providerId")]
        public string ProviderId { get; set; } = null;

            
                
        [JsonInclude, JsonPropertyName("userId")]
        public string UserId { get; set; } = null;

            
                
        [JsonInclude, JsonPropertyName("id")]
        public string Id { get; set; } = null;

            
                
        [JsonInclude, JsonPropertyName("active")]
        public bool Active { get; set; } = true;

            
                
        [JsonInclude, JsonPropertyName("createdAt")]
        public DateTime? CreatedAt { get; set; } = null;

            
                
        [JsonInclude, JsonPropertyName("updatedAt")]
        public DateTime? UpdatedAt { get; set; } = null;

                    
        public string Serialise()
        {
            var options = new JsonSerializerOptions { WriteIndented = true, IncludeFields = true };
            string jsonString = JsonSerializer.Serialize(this, options);
            return jsonString;
        }

        public BaseUserProvider<T1> Deserialise(string json)
        {
            
            var deserialised = CreateFromJson(json);

            
            ProviderMetadata = deserialised.ProviderMetadata;
            ProviderName = deserialised.ProviderName;
            ProviderId = deserialised.ProviderId;
            UserId = deserialised.UserId;
            Id = deserialised.Id;
            Active = deserialised.Active;
            CreatedAt = deserialised.CreatedAt;
            UpdatedAt = deserialised.UpdatedAt;
            return this;
        }
           

        public static BaseUserProvider<T1> CreateFromJson(string json)
        {
            return JsonSerializer.Deserialize<BaseUserProvider<T1>>(json);
        }

        public BaseUserProvider()
        {

        }
        
        public BaseUserProvider(string json)
        {
            Deserialise(json);
        }

        public override string ToString() {
            return Serialise();
        }
    }    
}

